name: Snyk Issue

on:
  schedule:
    - cron: '0 */12 * * *'

concurrency: snyk-issue

jobs:
  whitesource:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
      with:
        egress-policy: audit

    - name: checkout action
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        repository: snowflakedb/whitesource-actions
        token: ${{ secrets.WHITESOURCE_ACTION_TOKEN }}
        path: whitesource-actions
    - name: set-env
      run: echo "REPO=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV
    - name: Jira Creation
      uses: ./whitesource-actions/snyk-issue
      with:
        snyk_org: ${{ secrets.SNYK_ORG_ID }}
        snyk_token:  ${{ secrets.SNYK_GITHUB_INTEGRATION_TOKEN }}
        jira_token: ${{ secrets.JIRA_TOKEN }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

